- hosts: workstation
  roles:
  - dork.workstation
  - { role: dork.admin, admin_name: vagrant }
  - { role: dork.shell, shell_user: vagrant, shell_zsh_theme: Soliah }
  - { role: dork.shell, shell_user: root, shell_zsh_theme: mrtazz }
  # Remove the following line if you want to use dork only as remote control
  # for your server environment.
  - dork.host
