- hosts: dork-host
  vars_prompt:
  - name: project
    prompt: Project domain ([project].[instance])
    private: no

  - name: name
    prompt: Username
    private: no

  - name: password
    prompt: Password
    private: yes

  tasks:
  - htpasswd:
      path: /var/dork/auth/{{ project }}
      name: "{{ name }}"
      password: "{{ password }}"
