- hosts: server
  vars_prompt:
  - name: project
    prompt: Project directory (below /var/source)
    private: no

  - name: name
    prompt: Username
    private: no

  - name: password
    prompt: Password
    private: yes

  tasks:
  - htpasswd:
      path: /etc/nginx/.htpasswd-{{ project }}
      name: "{{ name }}"
      password: "{{ password }}"
