- hosts: server
  roles:
  - dork.shell
  - dork.host

  tasks:

  # Install 3rd party ansible roles
  - copy:
      src: /vagrant/roles.yml
      dest: /etc/ansible/roles.yml
    register: roles

  - shell: > 
      ansible-galaxy install
      --no-deps --force
      --role-file=/etc/ansible/roles.yml
      --roles-path=/etc/ansible/roles
    when: roles.changed

  # Synchronize custom ansible roles and playbooks
  - synchronize:
      src: /opt/{{ item }}/
      dest: /opt/{{ items }}
      recursive: yes
    with_items:
    - roles
    - playbooks
