- hosts: server
  roles:
  - dork.shell
  - dork.host

  tasks:

  # Install 3rd party ansible roles
  - stat:
      path: /vagrant
    register: vagrant
    delegate_to: 127.0.0.1
    changed_when: vagrant.stat.exists

  - copy:
      src: /vagrant/roles.yml
      dest: /etc/ansible/roles.yml
    register: roles
    when: vagrant.changed

  - shell: > 
      ansible-galaxy install
      --no-deps --force
      --role-file=/etc/ansible/roles.yml
      --roles-path=/etc/ansible/roles
    when: roles.changed

  # Synchronize custom ansible roles and playbooks
  - synchronize:
      src: /opt/{{ item }}/
      dest: /opt/{{ item }}
      recursive: yes
      delete: yes
    when: vagrant.changed
    with_items:
    - roles
    - playbooks

  # Synchronize authorized keys
  - file:
      path: /home/{{ dork_user }}/.ssh/authorized_keys.d
      state: directory

  - synchronize:
      src: authorized_keys.d/
      dest: /home/{{ dork_user }}/.ssh/authorized_keys.d/
      delete: yes
    register: keys

  - shell: cat /home/{{ dork_user }}/.ssh/authorized_keys.d/*.pub > /home/{{ dork_user }}/.ssh/authorized_keys
    when: keys.changed

  - include: setup-server-custom.yml
